export default function Terms() {
    return (<div className="container-px mx-auto max-w-3xl pb-24 pt-12 md:pb-32">
      <div className="eyebrow mb-6">
        <span className="h-1.5 w-1.5 rounded-full bg-pulse animate-blink-dot"/>
        MEMBERSHIP CHARTER
      </div>
      <h1 className="font-display text-display-md font-black tracking-tight text-ink mb-10">
        Terms of <span className="text-pulse">Service</span>.
      </h1>

      <div className="space-y-8 text-xs text-ink-dim leading-relaxed">
        <section className="space-y-3">
          <h3 className="font-display text-sm font-bold text-ink uppercase tracking-wider">1. Medical Liability Disclaimer</h3>
          <p className="border-l-2 border-pulse pl-4 italic text-ink">
            IMPORTANT: PulseX is a metric tracking and orchestration platform. We are not a medical board. Recommendations generated by our system or coaches should not replace professional clinical advice. Always consult a physician before conducting high-intensity cardiac training.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="font-display text-sm font-bold text-ink uppercase tracking-wider">2. Roster Access Rules</h3>
          <p>
            Users assigned to Trainer accounts agree that trainers have authorization to modify meal guides, suggest exercise workloads, and schedule calendar items. Abuse of messaging limits will result in immediate service termination.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="font-display text-sm font-bold text-ink uppercase tracking-wider">3. API & Script Scopes</h3>
          <p>
            You agree not to scraping telemetry metrics or reverse engineering our dynamic calculation modules. API access must adhere strictly to rate limits specified in user configurations.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="font-display text-sm font-bold text-ink uppercase tracking-wider">4. Payment & System Auditing</h3>
          <p>
            Subscription cycles auto-renew. Accounts failing verification or credit clearance will revert to base individual offline mode after a 3-day buffer window.
          </p>
        </section>
      </div>
    </div>);
}
